pipeline {
    agent any


    environment {
    SVC_ACCOUNT_KEY = credentials('terraform-auth')
  }
     
    stages {      

	stage('Set Terraform path') {
            steps {
                script {
                    def tfHome = tool name: 'Terraform'
                    env.PATH = "${tfHome}:${env.PATH}"
                }
                sh 'echo $SVC_ACCOUNT_KEY | base64 -d > ./Terraform tfvars/terraform.json'
		sh 'pwd'
                sh 'terraform --version'               
               
            }
        }
        
         stage('Provision infrastructure') {
		 steps {   
			 dir('Terraform tfvars')
			 {
                sh 'terraform init'
                sh 'terraform plan -var-file="instance.tfvars"'
                sh 'terraform apply -var-file="instance.tfvars" -auto-approve'
                             
             
			 }
        }
        }
        
      
      
    }
}
