pipeline {
    agent any
	//parameters {
	//	string(bane: 'TARGET_ENV', defaultValue: 'PROD', description: 'Environment')
	//}


    environment {
    SVC_ACCOUNT_KEY = credentials('terraform-auth')
  }
     
    stages {
        stage ('checkout'){
            steps {
                git branch: 'main', url: 'https://github.com/ishaqmdgcp/gcp-devops.git'
            }
        }
      
	     stage('PACKER') {
		    steps{
			    scripts{
				    //build (job: 'PACKER')
				    build(job: 'pipelines/PACKER', wait: false)
				    //parametes: [
					//    [$class: 'StringParameterValue', name 'FROM_BUILD', value: "${BUILD_NUMBER}" ]
					  //  ]
			    }
		    }
	    }

		stage('Set Terraform path') {
            steps {
                script {
                    def tfHome = tool name: 'Terraform'
                    env.PATH = "${tfHome}:${env.PATH}"
                }
                sh 'echo $SVC_ACCOUNT_KEY | base64 -d > ./VMInstance/terraform.json'
		sh 'pwd'
                sh 'terraform --version'               
               
            }
        }
	    
	   
        
         stage('Initialize Terraform') {
		 steps {  
			  dir('VMInstance')
			 {
                sh 'terraform init'
			 }
		 }
	 }
		
	stage('Terraform Plan') {
		 steps {  
			  dir('VMInstance')
			 {
          
		 sh 'terraform plan'
	
				
			 }
		 }
	}
					 
	stage('Terraform Action') {
		 steps {  
			  dir('VMInstance')
			 {
                //sh 'terraform $TF_ACTION $TF_APPROVE'
		// sh 'terraform plan'
		 sh 'terraform $TF_ACTION -auto-approve'
				
			 }
		 }
	}
      
	     //stage('Initialize Destroy') {
		// steps {  
		//	  dir('VMInstance')
		//	 {
                //sh 'sleep 60'
		//sh 'terraform destroy -auto-approve'
		//	 }
		 //}
	// }
}
}
